#!/bin/bash
#ddev-silent-no-warn

## Description: create a custom theme and install recipes, settings, export configuration
## Usage: quickstart
## Example: ddev quickstart

# install the site
vendor/bin/drush site:install --site-mail=no-reply.webservices@ubc.ca --account-mail=no-reply.webservices@ubc.ca --yes

# setup sitename
echo -e "Please enter the site name: "
read sitename

# setup themename
echo -e "Please enter a machine name for your new theme (lowercase and underscores only): "
read themename

cd ${DDEV_DOCROOT}

# Create a new theme
php ../vendor/bin/dr generate-theme "$themename"  --starterkit kraken --path themes/custom

# Run the main orchestration recipe
php ../vendor/bin/dr recipe ../recipes/ws-recipes -v

# Run the ckeditor bookmark recipe
php ../vendor/bin/dr recipe ../recipes/ws-recipes/ws-utility/utility-add-bookmark-button -v

# Run the ckeditor findreplace recipe
php ../vendor/bin/dr recipe ../recipes/ws-recipes/ws-utility/utility-add-findreplace-button -v

# Enable devel
drush pm:enable devel

# Set the site name and email address
drush config-set system.site name "$sitename" -y

# Set the site name in the kraken theme
drush config-set kraken.settings clf_unitname "$sitename" -y

# Set media_alias_display settings
drush config-set media_alias_display.settings media_bundles.audio audio -y
drush config-set media_alias_display.settings media_bundles.file file -y
drush config-set media_alias_display.settings media_bundles.image image -y
drush config-set media_alias_display.settings media_bundles.svg_icon svg_icon -y

# Remove unused role
drush config:delete "user.role.content_editor"
drush config:delete "system.action.user_add_role_action.content_editor"
drush config:delete "system.action.user_remove_role_action.content_editor"

# Delete unused Article, Basic Page and Comment entities - removed as 11.4 no longer installs these by default
# drush entity:delete node --bundle=article
# drush entity:delete node --bundle=page

# Delete Article, Basic Page and Comment types - removed as 11.4 no longer installs these by default
# drush eval "\Drupal::entityTypeManager()->getStorage('node_type')->load('page')->delete();"
# drush eval "\Drupal::entityTypeManager()->getStorage('node_type')->load('article')->delete();"
# drush eval "\Drupal::entityTypeManager()->getStorage('comment_type')->load('comment')->delete();"

# Disable comment and announcement modules
# drush pmu comment - removed as 11.4 no longer installs these by default
drush pmu announcements_feed

# Rebuild Permissions
drush php-eval 'node_access_rebuild();'

# Run any updates
drush updb -y

# Enable the update module
drush pm:install update -y

# Set the custom theme as the default theme
drush theme:enable "$themename" -y
drush config-set system.theme default "$themename" -y
drush config-set "$themename".settings clf_unitname "$sitename" -y
# drush theme:uninstall kraken -y

# Export the config
drush cex -y

# Provide a link to the user 1 password reset
drush uli

echo "All done - you can now reset the admin password above ^"