#!/bin/bash

## Description: run npm in default theme with provided arguments
## Usage: theme <arguments>
## Example: ddev theme run css

# find the current default theme
THEME=$(drush config:get system.theme default --format=string)
# Run npm in the OUC theme directory
cd /var/www/html/web/themes/custom/"$THEME"
npm "$@"